base_dataset_folder: /home/mila/x/xut/github/MGSM-Pro/src/dataset_creation/dataset
dataset_type: ic-names-numbers
language: 
  - chinese
  - english
  - french
  - igbo
  - japanese
  - swahili
  - twi
  - yoruba
prompt_id_to_use:
   - english
n_shots: 0
model_platform: vllm
model_name: google/gemma-3-4b-it
model_max_token: 4096
model_temperature: 0.1
result_basedir: ./path/to/result

total_num_variation: 2