base_dataset_folder: /path/to/dataset
dataset_type: original-mgsm
language: 
  - en
  - fr
  - ja
  - zh
prompt_id_to_use:
   - english
total_num_variation: 1
model_platform: gemini
model_name: gemini-3-pro-preview
thinking_budget: 1
model_max_token: 4096
model_temperature: 0.1
result_basedir: /path/to/result
