base_dataset_folder: /path/to/dataset
dataset_type: symbolic-names-numbers
language: 
  - amharic
  - chinese
  - english
  - french
  - igbo
  - japanese
  - swahili
  - twi
  - yoruba
prompt_id_to_use:
   - english
model_platform: gemini
model_name: gemini-2.0-flash
model_max_token: 4096
model_temperature: 0.1
result_basedir: /path/to/result

total_num_variation: 10