base_dataset_folder: /home/mila/x/xut/github/evaluation-pipeline/dataset
dataset_type: distribution-ic
language: 
  - french
model_platform: vllm
model_name: openai/gpt-oss-120b
model_max_token: 4096
model_temperature: 0.1
result_basedir: /home/mila/x/xut/github/evaluation-pipeline/result

total_num_variation: 10