base_dataset_folder: /home/mila/x/xut/github/evaluation-pipeline/dataset
dataset_type: original-mgsm
language: 
  - bn
  - de
#  - en
  - es
  - fr
  - ja
  - ru
  - sw
  - te
  - th
  - zh
model_platform: gemini
model_name: gemini-2.0-flash
model_max_token: 4096
model_temperature: 1.0
result_basedir: /home/mila/x/xut/github/evaluation-pipeline/result