base_dataset_folder: /home/mila/x/xut/github/evaluation-pipeline/dataset
dataset_type: original-afrimgsm
language: 
  - ibo
  - kin
  - lin
model_platform: gemini
model_name: gemini-2.5-flash
thinking_budget: 0
model_max_token: 4096
model_temperature: 1.0
result_basedir: /home/mila/x/xut/github/evaluation-pipeline/result